//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navision.WebApi.Approve {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", ConfigurationName="Approve.ApprovalsMgmt_Port")]
    public interface ApprovalsMgmt_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (OnRenameRecordInApprovalRequest_Result) of message OnRenameRecordInApprovalRequest_Result does not match the default value (OnRenameRecordInApprovalRequest)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:OnRenameRecordInApprovalReq" +
            "uest", ReplyAction="*")]
        Navision.WebApi.Approve.OnRenameRecordInApprovalRequest_Result OnRenameRecordInApprovalRequest(Navision.WebApi.Approve.OnRenameRecordInApprovalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:OnRenameRecordInApprovalReq" +
            "uest", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.OnRenameRecordInApprovalRequest_Result> OnRenameRecordInApprovalRequestAsync(Navision.WebApi.Approve.OnRenameRecordInApprovalRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (OnDeleteRecordInApprovalRequest_Result) of message OnDeleteRecordInApprovalRequest_Result does not match the default value (OnDeleteRecordInApprovalRequest)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:OnDeleteRecordInApprovalReq" +
            "uest", ReplyAction="*")]
        Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest_Result OnDeleteRecordInApprovalRequest(Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:OnDeleteRecordInApprovalReq" +
            "uest", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest_Result> OnDeleteRecordInApprovalRequestAsync(Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ApproveRecordApprovalRequest_Result) of message ApproveRecordApprovalRequest_Result does not match the default value (ApproveRecordApprovalRequest)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:ApproveRecordApprovalReques" +
            "t", ReplyAction="*")]
        Navision.WebApi.Approve.ApproveRecordApprovalRequest_Result ApproveRecordApprovalRequest(Navision.WebApi.Approve.ApproveRecordApprovalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:ApproveRecordApprovalReques" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.ApproveRecordApprovalRequest_Result> ApproveRecordApprovalRequestAsync(Navision.WebApi.Approve.ApproveRecordApprovalRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (RejectRecordApprovalRequest_Result) of message RejectRecordApprovalRequest_Result does not match the default value (RejectRecordApprovalRequest)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:RejectRecordApprovalRequest" +
            "", ReplyAction="*")]
        Navision.WebApi.Approve.RejectRecordApprovalRequest_Result RejectRecordApprovalRequest(Navision.WebApi.Approve.RejectRecordApprovalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:RejectRecordApprovalRequest" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.RejectRecordApprovalRequest_Result> RejectRecordApprovalRequestAsync(Navision.WebApi.Approve.RejectRecordApprovalRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DelegateRecordApprovalRequest_Result) of message DelegateRecordApprovalRequest_Result does not match the default value (DelegateRecordApprovalRequest)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:DelegateRecordApprovalReque" +
            "st", ReplyAction="*")]
        Navision.WebApi.Approve.DelegateRecordApprovalRequest_Result DelegateRecordApprovalRequest(Navision.WebApi.Approve.DelegateRecordApprovalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:DelegateRecordApprovalReque" +
            "st", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.DelegateRecordApprovalRequest_Result> DelegateRecordApprovalRequestAsync(Navision.WebApi.Approve.DelegateRecordApprovalRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsOverdueNotificationsWorkflowEnabled_Result) of message IsOverdueNotificationsWorkflowEnabled_Result does not match the default value (IsOverdueNotificationsWorkflowEnabled)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:IsOverdueNotificationsWorkf" +
            "lowEnabled", ReplyAction="*")]
        Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled_Result IsOverdueNotificationsWorkflowEnabled(Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:IsOverdueNotificationsWorkf" +
            "lowEnabled", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled_Result> IsOverdueNotificationsWorkflowEnabledAsync(Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled request);
        
        // CODEGEN: Generating message contract since the wrapper name (PostApprovalEntries_Result) of message PostApprovalEntries_Result does not match the default value (PostApprovalEntries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:PostApprovalEntries", ReplyAction="*")]
        Navision.WebApi.Approve.PostApprovalEntries_Result PostApprovalEntries(Navision.WebApi.Approve.PostApprovalEntries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:PostApprovalEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.PostApprovalEntries_Result> PostApprovalEntriesAsync(Navision.WebApi.Approve.PostApprovalEntries request);
        
        // CODEGEN: Generating message contract since the wrapper name (ShowPostedApprovalEntries_Result) of message ShowPostedApprovalEntries_Result does not match the default value (ShowPostedApprovalEntries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:ShowPostedApprovalEntries", ReplyAction="*")]
        Navision.WebApi.Approve.ShowPostedApprovalEntries_Result ShowPostedApprovalEntries(Navision.WebApi.Approve.ShowPostedApprovalEntries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:ShowPostedApprovalEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.ShowPostedApprovalEntries_Result> ShowPostedApprovalEntriesAsync(Navision.WebApi.Approve.ShowPostedApprovalEntries request);
        
        // CODEGEN: Generating message contract since the wrapper name (DeletePostedApprovalEntries_Result) of message DeletePostedApprovalEntries_Result does not match the default value (DeletePostedApprovalEntries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:DeletePostedApprovalEntries" +
            "", ReplyAction="*")]
        Navision.WebApi.Approve.DeletePostedApprovalEntries_Result DeletePostedApprovalEntries(Navision.WebApi.Approve.DeletePostedApprovalEntries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:DeletePostedApprovalEntries" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.DeletePostedApprovalEntries_Result> DeletePostedApprovalEntriesAsync(Navision.WebApi.Approve.DeletePostedApprovalEntries request);
        
        // CODEGEN: Generating message contract since the wrapper name (HasOpenApprovalEntriesForCurrentUser_Result) of message HasOpenApprovalEntriesForCurrentUser_Result does not match the default value (HasOpenApprovalEntriesForCurrentUser)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasOpenApprovalEntriesForCu" +
            "rrentUser", ReplyAction="*")]
        Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser_Result HasOpenApprovalEntriesForCurrentUser(Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasOpenApprovalEntriesForCu" +
            "rrentUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser_Result> HasOpenApprovalEntriesForCurrentUserAsync(Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser request);
        
        // CODEGEN: Generating message contract since the wrapper name (HasOpenApprovalEntries_Result) of message HasOpenApprovalEntries_Result does not match the default value (HasOpenApprovalEntries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasOpenApprovalEntries", ReplyAction="*")]
        Navision.WebApi.Approve.HasOpenApprovalEntries_Result HasOpenApprovalEntries(Navision.WebApi.Approve.HasOpenApprovalEntries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasOpenApprovalEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasOpenApprovalEntries_Result> HasOpenApprovalEntriesAsync(Navision.WebApi.Approve.HasOpenApprovalEntries request);
        
        // CODEGEN: Generating message contract since the wrapper name (HasOpenOrPendingApprovalEntries_Result) of message HasOpenOrPendingApprovalEntries_Result does not match the default value (HasOpenOrPendingApprovalEntries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasOpenOrPendingApprovalEnt" +
            "ries", ReplyAction="*")]
        Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries_Result HasOpenOrPendingApprovalEntries(Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasOpenOrPendingApprovalEnt" +
            "ries", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries_Result> HasOpenOrPendingApprovalEntriesAsync(Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries request);
        
        // CODEGEN: Generating message contract since the wrapper name (HasApprovalEntries_Result) of message HasApprovalEntries_Result does not match the default value (HasApprovalEntries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasApprovalEntries", ReplyAction="*")]
        Navision.WebApi.Approve.HasApprovalEntries_Result HasApprovalEntries(Navision.WebApi.Approve.HasApprovalEntries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasApprovalEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasApprovalEntries_Result> HasApprovalEntriesAsync(Navision.WebApi.Approve.HasApprovalEntries request);
        
        // CODEGEN: Generating message contract since the wrapper name (HasAnyOpenJournalLineApprovalEntries_Result) of message HasAnyOpenJournalLineApprovalEntries_Result does not match the default value (HasAnyOpenJournalLineApprovalEntries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasAnyOpenJournalLineApprov" +
            "alEntries", ReplyAction="*")]
        Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries_Result HasAnyOpenJournalLineApprovalEntries(Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:HasAnyOpenJournalLineApprov" +
            "alEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries_Result> HasAnyOpenJournalLineApprovalEntriesAsync(Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries request);
        
        // CODEGEN: Generating message contract since the wrapper name (RenameApprovalEntries_Result) of message RenameApprovalEntries_Result does not match the default value (RenameApprovalEntries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:RenameApprovalEntries", ReplyAction="*")]
        Navision.WebApi.Approve.RenameApprovalEntries_Result RenameApprovalEntries(Navision.WebApi.Approve.RenameApprovalEntries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:RenameApprovalEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.RenameApprovalEntries_Result> RenameApprovalEntriesAsync(Navision.WebApi.Approve.RenameApprovalEntries request);
        
        // CODEGEN: Generating message contract since the wrapper name (DeleteApprovalEntries_Result) of message DeleteApprovalEntries_Result does not match the default value (DeleteApprovalEntries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:DeleteApprovalEntries", ReplyAction="*")]
        Navision.WebApi.Approve.DeleteApprovalEntries_Result DeleteApprovalEntries(Navision.WebApi.Approve.DeleteApprovalEntries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:DeleteApprovalEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.DeleteApprovalEntries_Result> DeleteApprovalEntriesAsync(Navision.WebApi.Approve.DeleteApprovalEntries request);
        
        // CODEGEN: Generating message contract since the wrapper name (DeleteApprovalCommentLines_Result) of message DeleteApprovalCommentLines_Result does not match the default value (DeleteApprovalCommentLines)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:DeleteApprovalCommentLines", ReplyAction="*")]
        Navision.WebApi.Approve.DeleteApprovalCommentLines_Result DeleteApprovalCommentLines(Navision.WebApi.Approve.DeleteApprovalCommentLines request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:DeleteApprovalCommentLines", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.DeleteApprovalCommentLines_Result> DeleteApprovalCommentLinesAsync(Navision.WebApi.Approve.DeleteApprovalCommentLines request);
        
        // CODEGEN: Generating message contract since the wrapper name (CopyApprovalEntryQuoteToOrder_Result) of message CopyApprovalEntryQuoteToOrder_Result does not match the default value (CopyApprovalEntryQuoteToOrder)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:CopyApprovalEntryQuoteToOrd" +
            "er", ReplyAction="*")]
        Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder_Result CopyApprovalEntryQuoteToOrder(Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:CopyApprovalEntryQuoteToOrd" +
            "er", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder_Result> CopyApprovalEntryQuoteToOrderAsync(Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder request);
        
        // CODEGEN: Generating message contract since the wrapper name (OpenApprovalEntriesPage_Result) of message OpenApprovalEntriesPage_Result does not match the default value (OpenApprovalEntriesPage)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:OpenApprovalEntriesPage", ReplyAction="*")]
        Navision.WebApi.Approve.OpenApprovalEntriesPage_Result OpenApprovalEntriesPage(Navision.WebApi.Approve.OpenApprovalEntriesPage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:OpenApprovalEntriesPage", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.OpenApprovalEntriesPage_Result> OpenApprovalEntriesPageAsync(Navision.WebApi.Approve.OpenApprovalEntriesPage request);
        
        // CODEGEN: Generating message contract since the wrapper name (CanCancelApprovalForRecord_Result) of message CanCancelApprovalForRecord_Result does not match the default value (CanCancelApprovalForRecord)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:CanCancelApprovalForRecord", ReplyAction="*")]
        Navision.WebApi.Approve.CanCancelApprovalForRecord_Result CanCancelApprovalForRecord(Navision.WebApi.Approve.CanCancelApprovalForRecord request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt:CanCancelApprovalForRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.CanCancelApprovalForRecord_Result> CanCancelApprovalForRecordAsync(Navision.WebApi.Approve.CanCancelApprovalForRecord request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnRenameRecordInApprovalRequest", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class OnRenameRecordInApprovalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string oldRecordId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=1)]
        public string newRecordId;
        
        public OnRenameRecordInApprovalRequest() {
        }
        
        public OnRenameRecordInApprovalRequest(string oldRecordId, string newRecordId) {
            this.oldRecordId = oldRecordId;
            this.newRecordId = newRecordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnRenameRecordInApprovalRequest_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class OnRenameRecordInApprovalRequest_Result {
        
        public OnRenameRecordInApprovalRequest_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnDeleteRecordInApprovalRequest", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class OnDeleteRecordInApprovalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordIDToApprove;
        
        public OnDeleteRecordInApprovalRequest() {
        }
        
        public OnDeleteRecordInApprovalRequest(string recordIDToApprove) {
            this.recordIDToApprove = recordIDToApprove;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnDeleteRecordInApprovalRequest_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class OnDeleteRecordInApprovalRequest_Result {
        
        public OnDeleteRecordInApprovalRequest_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveRecordApprovalRequest", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class ApproveRecordApprovalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordID;
        
        public ApproveRecordApprovalRequest() {
        }
        
        public ApproveRecordApprovalRequest(string recordID) {
            this.recordID = recordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveRecordApprovalRequest_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class ApproveRecordApprovalRequest_Result {
        
        public ApproveRecordApprovalRequest_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectRecordApprovalRequest", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class RejectRecordApprovalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordID;
        
        public RejectRecordApprovalRequest() {
        }
        
        public RejectRecordApprovalRequest(string recordID) {
            this.recordID = recordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectRecordApprovalRequest_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class RejectRecordApprovalRequest_Result {
        
        public RejectRecordApprovalRequest_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DelegateRecordApprovalRequest", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class DelegateRecordApprovalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordID;
        
        public DelegateRecordApprovalRequest() {
        }
        
        public DelegateRecordApprovalRequest(string recordID) {
            this.recordID = recordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DelegateRecordApprovalRequest_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class DelegateRecordApprovalRequest_Result {
        
        public DelegateRecordApprovalRequest_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsOverdueNotificationsWorkflowEnabled", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class IsOverdueNotificationsWorkflowEnabled {
        
        public IsOverdueNotificationsWorkflowEnabled() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsOverdueNotificationsWorkflowEnabled_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class IsOverdueNotificationsWorkflowEnabled_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public bool return_value;
        
        public IsOverdueNotificationsWorkflowEnabled_Result() {
        }
        
        public IsOverdueNotificationsWorkflowEnabled_Result(bool return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class PostApprovalEntries {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string approvedRecordID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=1)]
        public string postedRecordID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=2)]
        public string postedDocNo;
        
        public PostApprovalEntries() {
        }
        
        public PostApprovalEntries(string approvedRecordID, string postedRecordID, string postedDocNo) {
            this.approvedRecordID = approvedRecordID;
            this.postedRecordID = postedRecordID;
            this.postedDocNo = postedDocNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class PostApprovalEntries_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public bool return_value;
        
        public PostApprovalEntries_Result() {
        }
        
        public PostApprovalEntries_Result(bool return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShowPostedApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class ShowPostedApprovalEntries {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string postedRecordID;
        
        public ShowPostedApprovalEntries() {
        }
        
        public ShowPostedApprovalEntries(string postedRecordID) {
            this.postedRecordID = postedRecordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShowPostedApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class ShowPostedApprovalEntries_Result {
        
        public ShowPostedApprovalEntries_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePostedApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class DeletePostedApprovalEntries {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string postedRecordID;
        
        public DeletePostedApprovalEntries() {
        }
        
        public DeletePostedApprovalEntries(string postedRecordID) {
            this.postedRecordID = postedRecordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePostedApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class DeletePostedApprovalEntries_Result {
        
        public DeletePostedApprovalEntries_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasOpenApprovalEntriesForCurrentUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasOpenApprovalEntriesForCurrentUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordID;
        
        public HasOpenApprovalEntriesForCurrentUser() {
        }
        
        public HasOpenApprovalEntriesForCurrentUser(string recordID) {
            this.recordID = recordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasOpenApprovalEntriesForCurrentUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasOpenApprovalEntriesForCurrentUser_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public bool return_value;
        
        public HasOpenApprovalEntriesForCurrentUser_Result() {
        }
        
        public HasOpenApprovalEntriesForCurrentUser_Result(bool return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasOpenApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasOpenApprovalEntries {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordID;
        
        public HasOpenApprovalEntries() {
        }
        
        public HasOpenApprovalEntries(string recordID) {
            this.recordID = recordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasOpenApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasOpenApprovalEntries_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public bool return_value;
        
        public HasOpenApprovalEntries_Result() {
        }
        
        public HasOpenApprovalEntries_Result(bool return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasOpenOrPendingApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasOpenOrPendingApprovalEntries {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordID;
        
        public HasOpenOrPendingApprovalEntries() {
        }
        
        public HasOpenOrPendingApprovalEntries(string recordID) {
            this.recordID = recordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasOpenOrPendingApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasOpenOrPendingApprovalEntries_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public bool return_value;
        
        public HasOpenOrPendingApprovalEntries_Result() {
        }
        
        public HasOpenOrPendingApprovalEntries_Result(bool return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasApprovalEntries {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordID;
        
        public HasApprovalEntries() {
        }
        
        public HasApprovalEntries(string recordID) {
            this.recordID = recordID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasApprovalEntries_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public bool return_value;
        
        public HasApprovalEntries_Result() {
        }
        
        public HasApprovalEntries_Result(bool return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasAnyOpenJournalLineApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasAnyOpenJournalLineApprovalEntries {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string journalTemplateName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=1)]
        public string journalBatchName;
        
        public HasAnyOpenJournalLineApprovalEntries() {
        }
        
        public HasAnyOpenJournalLineApprovalEntries(string journalTemplateName, string journalBatchName) {
            this.journalTemplateName = journalTemplateName;
            this.journalBatchName = journalBatchName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HasAnyOpenJournalLineApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class HasAnyOpenJournalLineApprovalEntries_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public bool return_value;
        
        public HasAnyOpenJournalLineApprovalEntries_Result() {
        }
        
        public HasAnyOpenJournalLineApprovalEntries_Result(bool return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RenameApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class RenameApprovalEntries {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string oldRecordId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=1)]
        public string newRecordId;
        
        public RenameApprovalEntries() {
        }
        
        public RenameApprovalEntries(string oldRecordId, string newRecordId) {
            this.oldRecordId = oldRecordId;
            this.newRecordId = newRecordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RenameApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class RenameApprovalEntries_Result {
        
        public RenameApprovalEntries_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class DeleteApprovalEntries {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordIDToApprove;
        
        public DeleteApprovalEntries() {
        }
        
        public DeleteApprovalEntries(string recordIDToApprove) {
            this.recordIDToApprove = recordIDToApprove;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class DeleteApprovalEntries_Result {
        
        public DeleteApprovalEntries_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteApprovalCommentLines", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class DeleteApprovalCommentLines {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recordIDToApprove;
        
        public DeleteApprovalCommentLines() {
        }
        
        public DeleteApprovalCommentLines(string recordIDToApprove) {
            this.recordIDToApprove = recordIDToApprove;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteApprovalCommentLines_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class DeleteApprovalCommentLines_Result {
        
        public DeleteApprovalCommentLines_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CopyApprovalEntryQuoteToOrder", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class CopyApprovalEntryQuoteToOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string fromRecID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=1)]
        public string toDocNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=2)]
        public string toRecID;
        
        public CopyApprovalEntryQuoteToOrder() {
        }
        
        public CopyApprovalEntryQuoteToOrder(string fromRecID, string toDocNo, string toRecID) {
            this.fromRecID = fromRecID;
            this.toDocNo = toDocNo;
            this.toRecID = toRecID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CopyApprovalEntryQuoteToOrder_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class CopyApprovalEntryQuoteToOrder_Result {
        
        public CopyApprovalEntryQuoteToOrder_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenApprovalEntriesPage", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class OpenApprovalEntriesPage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recId;
        
        public OpenApprovalEntriesPage() {
        }
        
        public OpenApprovalEntriesPage(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenApprovalEntriesPage_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class OpenApprovalEntriesPage_Result {
        
        public OpenApprovalEntriesPage_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CanCancelApprovalForRecord", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class CanCancelApprovalForRecord {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public string recID;
        
        public CanCancelApprovalForRecord() {
        }
        
        public CanCancelApprovalForRecord(string recID) {
            this.recID = recID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CanCancelApprovalForRecord_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", IsWrapped=true)]
    public partial class CanCancelApprovalForRecord_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ApprovalsMgmt", Order=0)]
        public bool return_value;
        
        public CanCancelApprovalForRecord_Result() {
        }
        
        public CanCancelApprovalForRecord_Result(bool return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApprovalsMgmt_PortChannel : Navision.WebApi.Approve.ApprovalsMgmt_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApprovalsMgmt_PortClient : System.ServiceModel.ClientBase<Navision.WebApi.Approve.ApprovalsMgmt_Port>, Navision.WebApi.Approve.ApprovalsMgmt_Port {
        
        public ApprovalsMgmt_PortClient() {
        }
        
        public ApprovalsMgmt_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApprovalsMgmt_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApprovalsMgmt_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApprovalsMgmt_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.OnRenameRecordInApprovalRequest_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.OnRenameRecordInApprovalRequest(Navision.WebApi.Approve.OnRenameRecordInApprovalRequest request) {
            return base.Channel.OnRenameRecordInApprovalRequest(request);
        }
        
        public void OnRenameRecordInApprovalRequest(string oldRecordId, string newRecordId) {
            Navision.WebApi.Approve.OnRenameRecordInApprovalRequest inValue = new Navision.WebApi.Approve.OnRenameRecordInApprovalRequest();
            inValue.oldRecordId = oldRecordId;
            inValue.newRecordId = newRecordId;
            Navision.WebApi.Approve.OnRenameRecordInApprovalRequest_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).OnRenameRecordInApprovalRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.OnRenameRecordInApprovalRequest_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.OnRenameRecordInApprovalRequestAsync(Navision.WebApi.Approve.OnRenameRecordInApprovalRequest request) {
            return base.Channel.OnRenameRecordInApprovalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.OnRenameRecordInApprovalRequest_Result> OnRenameRecordInApprovalRequestAsync(string oldRecordId, string newRecordId) {
            Navision.WebApi.Approve.OnRenameRecordInApprovalRequest inValue = new Navision.WebApi.Approve.OnRenameRecordInApprovalRequest();
            inValue.oldRecordId = oldRecordId;
            inValue.newRecordId = newRecordId;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).OnRenameRecordInApprovalRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.OnDeleteRecordInApprovalRequest(Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest request) {
            return base.Channel.OnDeleteRecordInApprovalRequest(request);
        }
        
        public void OnDeleteRecordInApprovalRequest(string recordIDToApprove) {
            Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest inValue = new Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest();
            inValue.recordIDToApprove = recordIDToApprove;
            Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).OnDeleteRecordInApprovalRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.OnDeleteRecordInApprovalRequestAsync(Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest request) {
            return base.Channel.OnDeleteRecordInApprovalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest_Result> OnDeleteRecordInApprovalRequestAsync(string recordIDToApprove) {
            Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest inValue = new Navision.WebApi.Approve.OnDeleteRecordInApprovalRequest();
            inValue.recordIDToApprove = recordIDToApprove;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).OnDeleteRecordInApprovalRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.ApproveRecordApprovalRequest_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.ApproveRecordApprovalRequest(Navision.WebApi.Approve.ApproveRecordApprovalRequest request) {
            return base.Channel.ApproveRecordApprovalRequest(request);
        }
        
        public void ApproveRecordApprovalRequest(string recordID) {
            Navision.WebApi.Approve.ApproveRecordApprovalRequest inValue = new Navision.WebApi.Approve.ApproveRecordApprovalRequest();
            inValue.recordID = recordID;
            Navision.WebApi.Approve.ApproveRecordApprovalRequest_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).ApproveRecordApprovalRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.ApproveRecordApprovalRequest_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.ApproveRecordApprovalRequestAsync(Navision.WebApi.Approve.ApproveRecordApprovalRequest request) {
            return base.Channel.ApproveRecordApprovalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.ApproveRecordApprovalRequest_Result> ApproveRecordApprovalRequestAsync(string recordID) {
            Navision.WebApi.Approve.ApproveRecordApprovalRequest inValue = new Navision.WebApi.Approve.ApproveRecordApprovalRequest();
            inValue.recordID = recordID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).ApproveRecordApprovalRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.RejectRecordApprovalRequest_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.RejectRecordApprovalRequest(Navision.WebApi.Approve.RejectRecordApprovalRequest request) {
            return base.Channel.RejectRecordApprovalRequest(request);
        }
        
        public void RejectRecordApprovalRequest(string recordID) {
            Navision.WebApi.Approve.RejectRecordApprovalRequest inValue = new Navision.WebApi.Approve.RejectRecordApprovalRequest();
            inValue.recordID = recordID;
            Navision.WebApi.Approve.RejectRecordApprovalRequest_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).RejectRecordApprovalRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.RejectRecordApprovalRequest_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.RejectRecordApprovalRequestAsync(Navision.WebApi.Approve.RejectRecordApprovalRequest request) {
            return base.Channel.RejectRecordApprovalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.RejectRecordApprovalRequest_Result> RejectRecordApprovalRequestAsync(string recordID) {
            Navision.WebApi.Approve.RejectRecordApprovalRequest inValue = new Navision.WebApi.Approve.RejectRecordApprovalRequest();
            inValue.recordID = recordID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).RejectRecordApprovalRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.DelegateRecordApprovalRequest_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.DelegateRecordApprovalRequest(Navision.WebApi.Approve.DelegateRecordApprovalRequest request) {
            return base.Channel.DelegateRecordApprovalRequest(request);
        }
        
        public void DelegateRecordApprovalRequest(string recordID) {
            Navision.WebApi.Approve.DelegateRecordApprovalRequest inValue = new Navision.WebApi.Approve.DelegateRecordApprovalRequest();
            inValue.recordID = recordID;
            Navision.WebApi.Approve.DelegateRecordApprovalRequest_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).DelegateRecordApprovalRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.DelegateRecordApprovalRequest_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.DelegateRecordApprovalRequestAsync(Navision.WebApi.Approve.DelegateRecordApprovalRequest request) {
            return base.Channel.DelegateRecordApprovalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.DelegateRecordApprovalRequest_Result> DelegateRecordApprovalRequestAsync(string recordID) {
            Navision.WebApi.Approve.DelegateRecordApprovalRequest inValue = new Navision.WebApi.Approve.DelegateRecordApprovalRequest();
            inValue.recordID = recordID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).DelegateRecordApprovalRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.IsOverdueNotificationsWorkflowEnabled(Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled request) {
            return base.Channel.IsOverdueNotificationsWorkflowEnabled(request);
        }
        
        public bool IsOverdueNotificationsWorkflowEnabled() {
            Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled inValue = new Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled();
            Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).IsOverdueNotificationsWorkflowEnabled(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.IsOverdueNotificationsWorkflowEnabledAsync(Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled request) {
            return base.Channel.IsOverdueNotificationsWorkflowEnabledAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled_Result> IsOverdueNotificationsWorkflowEnabledAsync() {
            Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled inValue = new Navision.WebApi.Approve.IsOverdueNotificationsWorkflowEnabled();
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).IsOverdueNotificationsWorkflowEnabledAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.PostApprovalEntries_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.PostApprovalEntries(Navision.WebApi.Approve.PostApprovalEntries request) {
            return base.Channel.PostApprovalEntries(request);
        }
        
        public bool PostApprovalEntries(string approvedRecordID, string postedRecordID, string postedDocNo) {
            Navision.WebApi.Approve.PostApprovalEntries inValue = new Navision.WebApi.Approve.PostApprovalEntries();
            inValue.approvedRecordID = approvedRecordID;
            inValue.postedRecordID = postedRecordID;
            inValue.postedDocNo = postedDocNo;
            Navision.WebApi.Approve.PostApprovalEntries_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).PostApprovalEntries(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.PostApprovalEntries_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.PostApprovalEntriesAsync(Navision.WebApi.Approve.PostApprovalEntries request) {
            return base.Channel.PostApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.PostApprovalEntries_Result> PostApprovalEntriesAsync(string approvedRecordID, string postedRecordID, string postedDocNo) {
            Navision.WebApi.Approve.PostApprovalEntries inValue = new Navision.WebApi.Approve.PostApprovalEntries();
            inValue.approvedRecordID = approvedRecordID;
            inValue.postedRecordID = postedRecordID;
            inValue.postedDocNo = postedDocNo;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).PostApprovalEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.ShowPostedApprovalEntries_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.ShowPostedApprovalEntries(Navision.WebApi.Approve.ShowPostedApprovalEntries request) {
            return base.Channel.ShowPostedApprovalEntries(request);
        }
        
        public void ShowPostedApprovalEntries(string postedRecordID) {
            Navision.WebApi.Approve.ShowPostedApprovalEntries inValue = new Navision.WebApi.Approve.ShowPostedApprovalEntries();
            inValue.postedRecordID = postedRecordID;
            Navision.WebApi.Approve.ShowPostedApprovalEntries_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).ShowPostedApprovalEntries(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.ShowPostedApprovalEntries_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.ShowPostedApprovalEntriesAsync(Navision.WebApi.Approve.ShowPostedApprovalEntries request) {
            return base.Channel.ShowPostedApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.ShowPostedApprovalEntries_Result> ShowPostedApprovalEntriesAsync(string postedRecordID) {
            Navision.WebApi.Approve.ShowPostedApprovalEntries inValue = new Navision.WebApi.Approve.ShowPostedApprovalEntries();
            inValue.postedRecordID = postedRecordID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).ShowPostedApprovalEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.DeletePostedApprovalEntries_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.DeletePostedApprovalEntries(Navision.WebApi.Approve.DeletePostedApprovalEntries request) {
            return base.Channel.DeletePostedApprovalEntries(request);
        }
        
        public void DeletePostedApprovalEntries(string postedRecordID) {
            Navision.WebApi.Approve.DeletePostedApprovalEntries inValue = new Navision.WebApi.Approve.DeletePostedApprovalEntries();
            inValue.postedRecordID = postedRecordID;
            Navision.WebApi.Approve.DeletePostedApprovalEntries_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).DeletePostedApprovalEntries(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.DeletePostedApprovalEntries_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.DeletePostedApprovalEntriesAsync(Navision.WebApi.Approve.DeletePostedApprovalEntries request) {
            return base.Channel.DeletePostedApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.DeletePostedApprovalEntries_Result> DeletePostedApprovalEntriesAsync(string postedRecordID) {
            Navision.WebApi.Approve.DeletePostedApprovalEntries inValue = new Navision.WebApi.Approve.DeletePostedApprovalEntries();
            inValue.postedRecordID = postedRecordID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).DeletePostedApprovalEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.HasOpenApprovalEntriesForCurrentUser(Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser request) {
            return base.Channel.HasOpenApprovalEntriesForCurrentUser(request);
        }
        
        public bool HasOpenApprovalEntriesForCurrentUser(string recordID) {
            Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser inValue = new Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser();
            inValue.recordID = recordID;
            Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasOpenApprovalEntriesForCurrentUser(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.HasOpenApprovalEntriesForCurrentUserAsync(Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser request) {
            return base.Channel.HasOpenApprovalEntriesForCurrentUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser_Result> HasOpenApprovalEntriesForCurrentUserAsync(string recordID) {
            Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser inValue = new Navision.WebApi.Approve.HasOpenApprovalEntriesForCurrentUser();
            inValue.recordID = recordID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasOpenApprovalEntriesForCurrentUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.HasOpenApprovalEntries_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.HasOpenApprovalEntries(Navision.WebApi.Approve.HasOpenApprovalEntries request) {
            return base.Channel.HasOpenApprovalEntries(request);
        }
        
        public bool HasOpenApprovalEntries(string recordID) {
            Navision.WebApi.Approve.HasOpenApprovalEntries inValue = new Navision.WebApi.Approve.HasOpenApprovalEntries();
            inValue.recordID = recordID;
            Navision.WebApi.Approve.HasOpenApprovalEntries_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasOpenApprovalEntries(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasOpenApprovalEntries_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.HasOpenApprovalEntriesAsync(Navision.WebApi.Approve.HasOpenApprovalEntries request) {
            return base.Channel.HasOpenApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.HasOpenApprovalEntries_Result> HasOpenApprovalEntriesAsync(string recordID) {
            Navision.WebApi.Approve.HasOpenApprovalEntries inValue = new Navision.WebApi.Approve.HasOpenApprovalEntries();
            inValue.recordID = recordID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasOpenApprovalEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.HasOpenOrPendingApprovalEntries(Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries request) {
            return base.Channel.HasOpenOrPendingApprovalEntries(request);
        }
        
        public bool HasOpenOrPendingApprovalEntries(string recordID) {
            Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries inValue = new Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries();
            inValue.recordID = recordID;
            Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasOpenOrPendingApprovalEntries(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.HasOpenOrPendingApprovalEntriesAsync(Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries request) {
            return base.Channel.HasOpenOrPendingApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries_Result> HasOpenOrPendingApprovalEntriesAsync(string recordID) {
            Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries inValue = new Navision.WebApi.Approve.HasOpenOrPendingApprovalEntries();
            inValue.recordID = recordID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasOpenOrPendingApprovalEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.HasApprovalEntries_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.HasApprovalEntries(Navision.WebApi.Approve.HasApprovalEntries request) {
            return base.Channel.HasApprovalEntries(request);
        }
        
        public bool HasApprovalEntries(string recordID) {
            Navision.WebApi.Approve.HasApprovalEntries inValue = new Navision.WebApi.Approve.HasApprovalEntries();
            inValue.recordID = recordID;
            Navision.WebApi.Approve.HasApprovalEntries_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasApprovalEntries(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasApprovalEntries_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.HasApprovalEntriesAsync(Navision.WebApi.Approve.HasApprovalEntries request) {
            return base.Channel.HasApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.HasApprovalEntries_Result> HasApprovalEntriesAsync(string recordID) {
            Navision.WebApi.Approve.HasApprovalEntries inValue = new Navision.WebApi.Approve.HasApprovalEntries();
            inValue.recordID = recordID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasApprovalEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.HasAnyOpenJournalLineApprovalEntries(Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries request) {
            return base.Channel.HasAnyOpenJournalLineApprovalEntries(request);
        }
        
        public bool HasAnyOpenJournalLineApprovalEntries(string journalTemplateName, string journalBatchName) {
            Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries inValue = new Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries();
            inValue.journalTemplateName = journalTemplateName;
            inValue.journalBatchName = journalBatchName;
            Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasAnyOpenJournalLineApprovalEntries(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.HasAnyOpenJournalLineApprovalEntriesAsync(Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries request) {
            return base.Channel.HasAnyOpenJournalLineApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries_Result> HasAnyOpenJournalLineApprovalEntriesAsync(string journalTemplateName, string journalBatchName) {
            Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries inValue = new Navision.WebApi.Approve.HasAnyOpenJournalLineApprovalEntries();
            inValue.journalTemplateName = journalTemplateName;
            inValue.journalBatchName = journalBatchName;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).HasAnyOpenJournalLineApprovalEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.RenameApprovalEntries_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.RenameApprovalEntries(Navision.WebApi.Approve.RenameApprovalEntries request) {
            return base.Channel.RenameApprovalEntries(request);
        }
        
        public void RenameApprovalEntries(string oldRecordId, string newRecordId) {
            Navision.WebApi.Approve.RenameApprovalEntries inValue = new Navision.WebApi.Approve.RenameApprovalEntries();
            inValue.oldRecordId = oldRecordId;
            inValue.newRecordId = newRecordId;
            Navision.WebApi.Approve.RenameApprovalEntries_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).RenameApprovalEntries(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.RenameApprovalEntries_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.RenameApprovalEntriesAsync(Navision.WebApi.Approve.RenameApprovalEntries request) {
            return base.Channel.RenameApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.RenameApprovalEntries_Result> RenameApprovalEntriesAsync(string oldRecordId, string newRecordId) {
            Navision.WebApi.Approve.RenameApprovalEntries inValue = new Navision.WebApi.Approve.RenameApprovalEntries();
            inValue.oldRecordId = oldRecordId;
            inValue.newRecordId = newRecordId;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).RenameApprovalEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.DeleteApprovalEntries_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.DeleteApprovalEntries(Navision.WebApi.Approve.DeleteApprovalEntries request) {
            return base.Channel.DeleteApprovalEntries(request);
        }
        
        public void DeleteApprovalEntries(string recordIDToApprove) {
            Navision.WebApi.Approve.DeleteApprovalEntries inValue = new Navision.WebApi.Approve.DeleteApprovalEntries();
            inValue.recordIDToApprove = recordIDToApprove;
            Navision.WebApi.Approve.DeleteApprovalEntries_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).DeleteApprovalEntries(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.DeleteApprovalEntries_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.DeleteApprovalEntriesAsync(Navision.WebApi.Approve.DeleteApprovalEntries request) {
            return base.Channel.DeleteApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.DeleteApprovalEntries_Result> DeleteApprovalEntriesAsync(string recordIDToApprove) {
            Navision.WebApi.Approve.DeleteApprovalEntries inValue = new Navision.WebApi.Approve.DeleteApprovalEntries();
            inValue.recordIDToApprove = recordIDToApprove;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).DeleteApprovalEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.DeleteApprovalCommentLines_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.DeleteApprovalCommentLines(Navision.WebApi.Approve.DeleteApprovalCommentLines request) {
            return base.Channel.DeleteApprovalCommentLines(request);
        }
        
        public void DeleteApprovalCommentLines(string recordIDToApprove) {
            Navision.WebApi.Approve.DeleteApprovalCommentLines inValue = new Navision.WebApi.Approve.DeleteApprovalCommentLines();
            inValue.recordIDToApprove = recordIDToApprove;
            Navision.WebApi.Approve.DeleteApprovalCommentLines_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).DeleteApprovalCommentLines(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.DeleteApprovalCommentLines_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.DeleteApprovalCommentLinesAsync(Navision.WebApi.Approve.DeleteApprovalCommentLines request) {
            return base.Channel.DeleteApprovalCommentLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.DeleteApprovalCommentLines_Result> DeleteApprovalCommentLinesAsync(string recordIDToApprove) {
            Navision.WebApi.Approve.DeleteApprovalCommentLines inValue = new Navision.WebApi.Approve.DeleteApprovalCommentLines();
            inValue.recordIDToApprove = recordIDToApprove;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).DeleteApprovalCommentLinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.CopyApprovalEntryQuoteToOrder(Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder request) {
            return base.Channel.CopyApprovalEntryQuoteToOrder(request);
        }
        
        public void CopyApprovalEntryQuoteToOrder(string fromRecID, string toDocNo, string toRecID) {
            Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder inValue = new Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder();
            inValue.fromRecID = fromRecID;
            inValue.toDocNo = toDocNo;
            inValue.toRecID = toRecID;
            Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).CopyApprovalEntryQuoteToOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.CopyApprovalEntryQuoteToOrderAsync(Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder request) {
            return base.Channel.CopyApprovalEntryQuoteToOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder_Result> CopyApprovalEntryQuoteToOrderAsync(string fromRecID, string toDocNo, string toRecID) {
            Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder inValue = new Navision.WebApi.Approve.CopyApprovalEntryQuoteToOrder();
            inValue.fromRecID = fromRecID;
            inValue.toDocNo = toDocNo;
            inValue.toRecID = toRecID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).CopyApprovalEntryQuoteToOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.OpenApprovalEntriesPage_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.OpenApprovalEntriesPage(Navision.WebApi.Approve.OpenApprovalEntriesPage request) {
            return base.Channel.OpenApprovalEntriesPage(request);
        }
        
        public void OpenApprovalEntriesPage(string recId) {
            Navision.WebApi.Approve.OpenApprovalEntriesPage inValue = new Navision.WebApi.Approve.OpenApprovalEntriesPage();
            inValue.recId = recId;
            Navision.WebApi.Approve.OpenApprovalEntriesPage_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).OpenApprovalEntriesPage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.OpenApprovalEntriesPage_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.OpenApprovalEntriesPageAsync(Navision.WebApi.Approve.OpenApprovalEntriesPage request) {
            return base.Channel.OpenApprovalEntriesPageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.OpenApprovalEntriesPage_Result> OpenApprovalEntriesPageAsync(string recId) {
            Navision.WebApi.Approve.OpenApprovalEntriesPage inValue = new Navision.WebApi.Approve.OpenApprovalEntriesPage();
            inValue.recId = recId;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).OpenApprovalEntriesPageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.Approve.CanCancelApprovalForRecord_Result Navision.WebApi.Approve.ApprovalsMgmt_Port.CanCancelApprovalForRecord(Navision.WebApi.Approve.CanCancelApprovalForRecord request) {
            return base.Channel.CanCancelApprovalForRecord(request);
        }
        
        public bool CanCancelApprovalForRecord(string recID) {
            Navision.WebApi.Approve.CanCancelApprovalForRecord inValue = new Navision.WebApi.Approve.CanCancelApprovalForRecord();
            inValue.recID = recID;
            Navision.WebApi.Approve.CanCancelApprovalForRecord_Result retVal = ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).CanCancelApprovalForRecord(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.Approve.CanCancelApprovalForRecord_Result> Navision.WebApi.Approve.ApprovalsMgmt_Port.CanCancelApprovalForRecordAsync(Navision.WebApi.Approve.CanCancelApprovalForRecord request) {
            return base.Channel.CanCancelApprovalForRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.Approve.CanCancelApprovalForRecord_Result> CanCancelApprovalForRecordAsync(string recID) {
            Navision.WebApi.Approve.CanCancelApprovalForRecord inValue = new Navision.WebApi.Approve.CanCancelApprovalForRecord();
            inValue.recID = recID;
            return ((Navision.WebApi.Approve.ApprovalsMgmt_Port)(this)).CanCancelApprovalForRecordAsync(inValue);
        }
    }
}
