//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navision.WebApi.RecordLink {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", ConfigurationName="RecordLink.RecordLinkPage_Port")]
    public interface RecordLinkPage_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.Read_Result Read(Navision.WebApi.RecordLink.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Read_Result> ReadAsync(Navision.WebApi.RecordLink.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.ReadByRecId_Result ReadByRecId(Navision.WebApi.RecordLink.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.ReadByRecId_Result> ReadByRecIdAsync(Navision.WebApi.RecordLink.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.ReadMultiple_Result ReadMultiple(Navision.WebApi.RecordLink.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.ReadMultiple_Result> ReadMultipleAsync(Navision.WebApi.RecordLink.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.IsUpdated_Result IsUpdated(Navision.WebApi.RecordLink.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.IsUpdated_Result> IsUpdatedAsync(Navision.WebApi.RecordLink.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.GetRecIdFromKey_Result GetRecIdFromKey(Navision.WebApi.RecordLink.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(Navision.WebApi.RecordLink.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.Create_Result Create(Navision.WebApi.RecordLink.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Create_Result> CreateAsync(Navision.WebApi.RecordLink.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.CreateMultiple_Result CreateMultiple(Navision.WebApi.RecordLink.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.CreateMultiple_Result> CreateMultipleAsync(Navision.WebApi.RecordLink.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.Update_Result Update(Navision.WebApi.RecordLink.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Update_Result> UpdateAsync(Navision.WebApi.RecordLink.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.UpdateMultiple_Result UpdateMultiple(Navision.WebApi.RecordLink.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.UpdateMultiple_Result> UpdateMultipleAsync(Navision.WebApi.RecordLink.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Navision.WebApi.RecordLink.Delete_Result Delete(Navision.WebApi.RecordLink.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recordlinkpage:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Delete_Result> DeleteAsync(Navision.WebApi.RecordLink.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage")]
    public partial class RecordLinkPage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int link_IDField;
        
        private bool link_IDFieldSpecified;
        
        private string record_IDField;
        
        private string uRL1Field;
        
        private string uRL2Field;
        
        private string uRL3Field;
        
        private string uRL4Field;
        
        private string descriptionField;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private string user_IDField;
        
        private string companyField;
        
        private bool notifyField;
        
        private bool notifyFieldSpecified;
        
        private string to_User_IDField;
        
        private string commentaireField;
        
        private int statutField;
        
        private bool statutFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Link_ID {
            get {
                return this.link_IDField;
            }
            set {
                this.link_IDField = value;
                this.RaisePropertyChanged("Link_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Link_IDSpecified {
            get {
                return this.link_IDFieldSpecified;
            }
            set {
                this.link_IDFieldSpecified = value;
                this.RaisePropertyChanged("Link_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Record_ID {
            get {
                return this.record_IDField;
            }
            set {
                this.record_IDField = value;
                this.RaisePropertyChanged("Record_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string URL1 {
            get {
                return this.uRL1Field;
            }
            set {
                this.uRL1Field = value;
                this.RaisePropertyChanged("URL1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string URL2 {
            get {
                return this.uRL2Field;
            }
            set {
                this.uRL2Field = value;
                this.RaisePropertyChanged("URL2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string URL3 {
            get {
                return this.uRL3Field;
            }
            set {
                this.uRL3Field = value;
                this.RaisePropertyChanged("URL3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string URL4 {
            get {
                return this.uRL4Field;
            }
            set {
                this.uRL4Field = value;
                this.RaisePropertyChanged("URL4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Type Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
                this.RaisePropertyChanged("CreatedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string User_ID {
            get {
                return this.user_IDField;
            }
            set {
                this.user_IDField = value;
                this.RaisePropertyChanged("User_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool Notify {
            get {
                return this.notifyField;
            }
            set {
                this.notifyField = value;
                this.RaisePropertyChanged("Notify");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotifySpecified {
            get {
                return this.notifyFieldSpecified;
            }
            set {
                this.notifyFieldSpecified = value;
                this.RaisePropertyChanged("NotifySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string To_User_ID {
            get {
                return this.to_User_IDField;
            }
            set {
                this.to_User_IDField = value;
                this.RaisePropertyChanged("To_User_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Commentaire {
            get {
                return this.commentaireField;
            }
            set {
                this.commentaireField = value;
                this.RaisePropertyChanged("Commentaire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Statut {
            get {
                return this.statutField;
            }
            set {
                this.statutField = value;
                this.RaisePropertyChanged("Statut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatutSpecified {
            get {
                return this.statutFieldSpecified;
            }
            set {
                this.statutFieldSpecified = value;
                this.RaisePropertyChanged("StatutSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage")]
    public enum Type {
        
        /// <remarks/>
        Link,
        
        /// <remarks/>
        Note,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage")]
    public partial class RecordLinkPage_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RecordLinkPage_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RecordLinkPage_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage")]
    public enum RecordLinkPage_Fields {
        
        /// <remarks/>
        Link_ID,
        
        /// <remarks/>
        Record_ID,
        
        /// <remarks/>
        URL1,
        
        /// <remarks/>
        URL2,
        
        /// <remarks/>
        URL3,
        
        /// <remarks/>
        URL4,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Type,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        User_ID,
        
        /// <remarks/>
        Company,
        
        /// <remarks/>
        Notify,
        
        /// <remarks/>
        To_User_ID,
        
        /// <remarks/>
        Commentaire,
        
        /// <remarks/>
        Statut,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public int Link_ID;
        
        public Read() {
        }
        
        public Read(int Link_ID) {
            this.Link_ID = Link_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage;
        
        public Read_Result() {
        }
        
        public Read_Result(Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage) {
            this.RecordLinkPage = RecordLinkPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage) {
            this.RecordLinkPage = RecordLinkPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public Navision.WebApi.RecordLink.RecordLinkPage_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(Navision.WebApi.RecordLink.RecordLinkPage_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Navision.WebApi.RecordLink.RecordLinkPage[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(Navision.WebApi.RecordLink.RecordLinkPage[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage;
        
        public Create() {
        }
        
        public Create(Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage) {
            this.RecordLinkPage = RecordLinkPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage;
        
        public Create_Result() {
        }
        
        public Create_Result(Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage) {
            this.RecordLinkPage = RecordLinkPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List) {
            this.RecordLinkPage_List = RecordLinkPage_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List) {
            this.RecordLinkPage_List = RecordLinkPage_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage;
        
        public Update() {
        }
        
        public Update(Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage) {
            this.RecordLinkPage = RecordLinkPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage;
        
        public Update_Result() {
        }
        
        public Update_Result(Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage) {
            this.RecordLinkPage = RecordLinkPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List) {
            this.RecordLinkPage_List = RecordLinkPage_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List) {
            this.RecordLinkPage_List = RecordLinkPage_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/recordlinkpage", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecordLinkPage_PortChannel : Navision.WebApi.RecordLink.RecordLinkPage_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecordLinkPage_PortClient : System.ServiceModel.ClientBase<Navision.WebApi.RecordLink.RecordLinkPage_Port>, Navision.WebApi.RecordLink.RecordLinkPage_Port {
        
        public RecordLinkPage_PortClient() {
        }
        
        public RecordLinkPage_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecordLinkPage_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordLinkPage_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordLinkPage_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.Read_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.Read(Navision.WebApi.RecordLink.Read request) {
            return base.Channel.Read(request);
        }
        
        public Navision.WebApi.RecordLink.RecordLinkPage Read(int Link_ID) {
            Navision.WebApi.RecordLink.Read inValue = new Navision.WebApi.RecordLink.Read();
            inValue.Link_ID = Link_ID;
            Navision.WebApi.RecordLink.Read_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).Read(inValue);
            return retVal.RecordLinkPage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Read_Result> Navision.WebApi.RecordLink.RecordLinkPage_Port.ReadAsync(Navision.WebApi.RecordLink.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Read_Result> ReadAsync(int Link_ID) {
            Navision.WebApi.RecordLink.Read inValue = new Navision.WebApi.RecordLink.Read();
            inValue.Link_ID = Link_ID;
            return ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.ReadByRecId_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.ReadByRecId(Navision.WebApi.RecordLink.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public Navision.WebApi.RecordLink.RecordLinkPage ReadByRecId(string recId) {
            Navision.WebApi.RecordLink.ReadByRecId inValue = new Navision.WebApi.RecordLink.ReadByRecId();
            inValue.recId = recId;
            Navision.WebApi.RecordLink.ReadByRecId_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).ReadByRecId(inValue);
            return retVal.RecordLinkPage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.ReadByRecId_Result> Navision.WebApi.RecordLink.RecordLinkPage_Port.ReadByRecIdAsync(Navision.WebApi.RecordLink.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            Navision.WebApi.RecordLink.ReadByRecId inValue = new Navision.WebApi.RecordLink.ReadByRecId();
            inValue.recId = recId;
            return ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.ReadMultiple_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.ReadMultiple(Navision.WebApi.RecordLink.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public Navision.WebApi.RecordLink.RecordLinkPage[] ReadMultiple(Navision.WebApi.RecordLink.RecordLinkPage_Filter[] filter, string bookmarkKey, int setSize) {
            Navision.WebApi.RecordLink.ReadMultiple inValue = new Navision.WebApi.RecordLink.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            Navision.WebApi.RecordLink.ReadMultiple_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.ReadMultiple_Result> Navision.WebApi.RecordLink.RecordLinkPage_Port.ReadMultipleAsync(Navision.WebApi.RecordLink.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.ReadMultiple_Result> ReadMultipleAsync(Navision.WebApi.RecordLink.RecordLinkPage_Filter[] filter, string bookmarkKey, int setSize) {
            Navision.WebApi.RecordLink.ReadMultiple inValue = new Navision.WebApi.RecordLink.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.IsUpdated_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.IsUpdated(Navision.WebApi.RecordLink.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            Navision.WebApi.RecordLink.IsUpdated inValue = new Navision.WebApi.RecordLink.IsUpdated();
            inValue.Key = Key;
            Navision.WebApi.RecordLink.IsUpdated_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.IsUpdated_Result> Navision.WebApi.RecordLink.RecordLinkPage_Port.IsUpdatedAsync(Navision.WebApi.RecordLink.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.IsUpdated_Result> IsUpdatedAsync(string Key) {
            Navision.WebApi.RecordLink.IsUpdated inValue = new Navision.WebApi.RecordLink.IsUpdated();
            inValue.Key = Key;
            return ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.GetRecIdFromKey_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.GetRecIdFromKey(Navision.WebApi.RecordLink.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            Navision.WebApi.RecordLink.GetRecIdFromKey inValue = new Navision.WebApi.RecordLink.GetRecIdFromKey();
            inValue.Key = Key;
            Navision.WebApi.RecordLink.GetRecIdFromKey_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.GetRecIdFromKey_Result> Navision.WebApi.RecordLink.RecordLinkPage_Port.GetRecIdFromKeyAsync(Navision.WebApi.RecordLink.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            Navision.WebApi.RecordLink.GetRecIdFromKey inValue = new Navision.WebApi.RecordLink.GetRecIdFromKey();
            inValue.Key = Key;
            return ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.Create_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.Create(Navision.WebApi.RecordLink.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage) {
            Navision.WebApi.RecordLink.Create inValue = new Navision.WebApi.RecordLink.Create();
            inValue.RecordLinkPage = RecordLinkPage;
            Navision.WebApi.RecordLink.Create_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).Create(inValue);
            RecordLinkPage = retVal.RecordLinkPage;
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Create_Result> CreateAsync(Navision.WebApi.RecordLink.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.CreateMultiple_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.CreateMultiple(Navision.WebApi.RecordLink.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List) {
            Navision.WebApi.RecordLink.CreateMultiple inValue = new Navision.WebApi.RecordLink.CreateMultiple();
            inValue.RecordLinkPage_List = RecordLinkPage_List;
            Navision.WebApi.RecordLink.CreateMultiple_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).CreateMultiple(inValue);
            RecordLinkPage_List = retVal.RecordLinkPage_List;
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.CreateMultiple_Result> CreateMultipleAsync(Navision.WebApi.RecordLink.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.Update_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.Update(Navision.WebApi.RecordLink.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref Navision.WebApi.RecordLink.RecordLinkPage RecordLinkPage) {
            Navision.WebApi.RecordLink.Update inValue = new Navision.WebApi.RecordLink.Update();
            inValue.RecordLinkPage = RecordLinkPage;
            Navision.WebApi.RecordLink.Update_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).Update(inValue);
            RecordLinkPage = retVal.RecordLinkPage;
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Update_Result> UpdateAsync(Navision.WebApi.RecordLink.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.UpdateMultiple_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.UpdateMultiple(Navision.WebApi.RecordLink.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref Navision.WebApi.RecordLink.RecordLinkPage[] RecordLinkPage_List) {
            Navision.WebApi.RecordLink.UpdateMultiple inValue = new Navision.WebApi.RecordLink.UpdateMultiple();
            inValue.RecordLinkPage_List = RecordLinkPage_List;
            Navision.WebApi.RecordLink.UpdateMultiple_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).UpdateMultiple(inValue);
            RecordLinkPage_List = retVal.RecordLinkPage_List;
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.UpdateMultiple_Result> UpdateMultipleAsync(Navision.WebApi.RecordLink.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Navision.WebApi.RecordLink.Delete_Result Navision.WebApi.RecordLink.RecordLinkPage_Port.Delete(Navision.WebApi.RecordLink.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            Navision.WebApi.RecordLink.Delete inValue = new Navision.WebApi.RecordLink.Delete();
            inValue.Key = Key;
            Navision.WebApi.RecordLink.Delete_Result retVal = ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Delete_Result> Navision.WebApi.RecordLink.RecordLinkPage_Port.DeleteAsync(Navision.WebApi.RecordLink.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Navision.WebApi.RecordLink.Delete_Result> DeleteAsync(string Key) {
            Navision.WebApi.RecordLink.Delete inValue = new Navision.WebApi.RecordLink.Delete();
            inValue.Key = Key;
            return ((Navision.WebApi.RecordLink.RecordLinkPage_Port)(this)).DeleteAsync(inValue);
        }
    }
}
